# Generated by Django 5.1.1 on 2024-10-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
