# Generated by Django 5.0.6 on 2024-10-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0004_alter_comment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='default-avatar.jpg', upload_to='avatars/'),
        ),
    ]
