# Generated by Django 5.0.6 on 2024-10-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0005_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
